export const FETCH_USER_DETAIL_SAGAS = 'FETCH_USER_DETAIL_SAGAS';
export const ACTIVE_LOCATION_SAGAS = 'ACTIVE_LOCATION_SAGAS';
export const RECEIVE_PRIZE_SAGAS = 'RECEIVE_PRIZE_SAGAS';
export const UPDATE_USER_DETAIL = 'UPDATE_USER_DETAIL';
export const UPDATE_USER_PRIZE = 'UPDATE_USER_PRIZE';
export const UPDATE_VISITED_LOCATION = 'UPDATE_VISITED_LOCATION';
